/* Consts*/
#define PLAYSOUND
#define DEBUG
#define TABLE_SIZE 360
#define AMPLITUDE 7.5
#define BASE_FREQUENCY 8.0 // Hz

typedef struct {
  uint8_t *wave;
  uint16_t length;
} waveLookup;

/* Function prototypes */
void generateSinLookupTable();
int getSinValue();

/* Vars */
int sinLookupTable[TABLE_SIZE];
float currentPhase = 0;
long lastUpdateTime;

void setup() {
  Serial.begin(9600);
  DDRB = DDRB | 0b1111; // Sets pins 8, 9, 10, 11 as output
  pinMode(A0, INPUT);
  delay(2000);
  generateSinLookupTable(); // Fills table fields for sin
  lastUpdateTime = 0;
}

void loop() {
  updatePhase(BASE_FREQUENCY);
  int pos = getSinValue();
  setSpeaker(pos);
  Serial.print("output:");
  Serial.print(pos);
  Serial.print("input:");
  Serial.println(analogRead(A0));

  delay(5);
}

/* Function generated by CHATGPT, fills lookup table at startup */
/* Might be slightly faster to have the lookup table prefilled but that would look kind of weird. */
void generateSinLookupTable() {
  for (int i = 0; i < TABLE_SIZE; i++) {
    float radian = i * M_PI / 180.0;
    sinLookupTable[i] = round((sin(radian) * AMPLITUDE) + AMPLITUDE);
  }
}

// also generated by chatgpt after getting it to fix code
int getWaveValue(waveLookup w) {
  return sinLookupTable[round(currentPhase) % 360];
}

void updatePhase(float frequency) {
  unsigned long currentTime = millis();
  unsigned long elapsedTime = currentTime - lastUpdateTime;

  // Calculate phase increment based on frequency
  float phaseIncrement = (360.0 * frequency * elapsedTime) / 1000.0;
  currentPhase = fmod(phaseIncrement + currentPhase, 360.0);
 
  // Update last update time
  lastUpdateTime = currentTime;
}

// I don't fully understand what portB is with arduino. I know it's a lot faster than digitalwrite() and I'm not complaining.
void setSpeaker(uint8_t position) {
  PORTB = position & 0b1111;
}